name: Frontend CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-react-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or your current Node.js version

      - name: Install dependencies
        run: |
          npm ci # use `npm install` if you're not using a lock file
        # Or for yarn:
        # run: yarn install

      - name: Run tests
        run: |
          npm test -- --ci --watchAll=false
        # Or for yarn:
        # run: yarn test --ci --watchAll=false
